@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

title Prettier Container Diagram

Person(developer, "Developer", "Person that interacts with the code")


System_Ext(code_editor, "IDE", "Editor that contains user's code and calls Prettier to format it")
System_Ext(file_syst, "File system", "Modules that manage the static configuration files in the project")

System_Boundary(prettier, "Prettier"){

    Container(cli, "CLI", "Command line translator and application", "Manages the terminal commands written by the user")
    Container(core_engine, "Core engine", "Prettier's core functions", "Receives a string, formats it and returns the formatted string")
    Container(language_plugin, "Language plugin", "Programming language translator", "Contains different ways of translating different programming languages")
}

Rel(developer, cli, "Runs terminal commands")
Rel(developer, code_editor, "Writes code in")
Rel(code_editor, file_syst, "Reads/Writes source files and configuration")

Rel(cli, file_syst, "Reads raw files/configs and overwrites them with formatted code")
Rel(cli, core_engine, "Passes the translated command")

Rel(core_engine,language_plugin,  "Asks for the right translator for the code")
Rel(code_editor, core_engine, "Calls Prettier's Javascript API")



@enduml